### ISSUE TITLE
Black border placed around widgets in screenshots

### ISSUE THREAD

**Issue by mstagitis** [eBay/flutter_glove_box#104]
I have a simple Flutter widget test in which I render a BottomNavigationBar (Android) with a few items. The page content is blank (for now). The screenshot resulting from this test shows a thick black border around the BottomNavigationBar (image below); however, I do not see this border when running on an emulator or real device. I am also seeing this border appear around other widgets, such as AlertDialog, in other tests.

Is there a way to remove this border from the screenshot? My guess is that this border is somehow related to the widget tree's "focus".

Thanks ahead of time!
- Matt

![tabs_screen_initial_load_on_android](https://user-images.githubusercontent.com/9640440/113383632-32d26400-9339-11eb-94fc-f725b1264c2d.png)

**Comment by mZadorskii** [comment]
Might be the shadows. What is your value for  debugDisableShadows?

**Comment by tsimbalar** [comment]
Shadows are disabled by default.

Take a look at https://github.com/eBay/flutter_glove_box/pull/75

**Comment by coreysprague** [comment]
Thanks @tsimbalar .Closing as this is the default behavior of flutter and there are options to enable proper shadow support.
