### ISSUE TITLE
Different rendering between Unix amd64 and arm64

### ISSUE THREAD

**Issue by gwennguihal** [eBay/flutter_glove_box#107]
We are used a docker image to run flutter test to avoid font rendering issues according the OS used by developers (mac, unix or windows).
Recently, we have been tried a Mac Mini M1. We generated also a new docker image based on arm64: 

DockerFile for arm64:
```
FROM arm64v8/ubuntu:20.04

RUN apt-get update && \
    apt-get install -y bash curl file git unzip xz-utils zip libglu1-mesa

RUN git clone https://github.com/flutter/flutter.git -b "2.2.0" --depth 1

ENV PATH="$PATH:/flutter/bin"

RUN flutter config --no-analytics && \
    flutter precache
```

DockerFile for amd64:
```
FROM amd64/ubuntu:20.04

RUN apt-get update && \
    apt-get install -y bash curl file git unzip xz-utils zip libglu1-mesa

RUN git clone https://github.com/flutter/flutter.git -b "2.2.0" --depth 1

ENV PATH="$PATH:/flutter/bin"

RUN flutter config --no-analytics && \
    flutter precache
```

But golden tests failed on several svgs between both architectures (we are used flutter_svg).

Here an isolated diff:

![disconnected_user Pixel_4_XL_isolatedDiff](https://user-images.githubusercontent.com/292125/119833083-16991080-beff-11eb-951c-f87e2d73fc69.png)

Is there a solution to solve that ?

Thanks

**Comment by nilsreichardt** [comment]
I think this is related to: https://github.com/flutter/flutter/issues/36667#issuecomment-521335243

**Comment by coreysprague** [comment]
@gwennguihal Unfortunately this is something out of our control and is a characteristic of the flutter framework itself. I think the best bet is to pick a singular platform/architecture to be the source of truth for goldens when it comes to text/svg. The alternative is you could try to maintain two distinct copies (leverage CI that can generate both, and developers can lean on their platform of choice to compare). We do provide hooks so if you wanted to suffix your golden file names with the architecture, I believe you could?
