### ISSUE TITLE
Goldens for different devices seem to influence each other. 

### ISSUE THREAD

**Issue by marcoAtEnvidual** [eBay/flutter_glove_box#108]
The Goldens look as follows if I run them with respectively.

```
..overrideDevicesForAllScenarios(devices: [
        Device.iphone11,
        // Device.phone,
      ])
      
      
..overrideDevicesForAllScenarios(devices: [
        Device.phone,
      ])

```
<img width="200" alt="Screenshot 2021-06-11 at 14 21 08" src="https://user-images.githubusercontent.com/84321534/121688591-ed15e280-cac3-11eb-9922-817d3a71c4de.png">
<img width="200" alt="Screenshot 2021-06-11 at 14 50 21" src="https://user-images.githubusercontent.com/84321534/121688990-6281b300-cac4-11eb-84a9-34f24a8dd4c2.png">

Running them with the following setup messes up both tests. 
```
..overrideDevicesForAllScenarios(devices: [
        Device.iphone11,
        Device.phone,
      ])

```

<img width="400" alt="Screenshot 2021-06-11 at 14 49 49" src="https://user-images.githubusercontent.com/84321534/121688948-539b0080-cac4-11eb-8627-4a65f671d0ab.png">

So the tests seem to influence each other :S

**Comment by coreysprague** [comment]
Thanks for reporting @marcoAtEnvidual . To be honest, I haven't looked super closely at DeviceBuilder, but I'll take a look.

I'd be interested in knowing if the same behavior occurs if you use the multiScreenGolden assertion.

**Comment by marcoAtEnvidual** [comment]
I'll check :)

**Comment by marcoAtEnvidual** [comment]
@coreysprague multiScreenGolden gives me everything in separate files. I only have one scenario to test on multiple devices. So the same behaviour occurs as with the DeviceBuilder that everything looks fine if I have them in separate files

**Comment by tsimbalar** [comment]
@marcoAtEnvidual  do you maybe use `MediaQuery` or that sort of stuff in your widget ? 

I think the `DeviceBuilder` approach really just creates a "bigger widget" in which each rectangle ends up being a page ... so they are in the same "widget tree" I believe. 

FYI we've been using `DeviceBuilder` without issues in our project (we have about 30-40 of those, with 4 difference device screens in each), and haven't seen this sort of interference 🤔

**Comment by marcoAtEnvidual** [comment]
@tsimbalar oh ;D yes I am. thanks :)

**Comment by lunaticcoding** [comment]
@coreysprague I found a fix for it and created a PR :D let me know what you think.
