### ISSUE TITLE
Problem running goldens tests after flutter 2.2.1 update

### ISSUE THREAD

**Issue by ansolantz** [eBay/flutter_glove_box#109]
Hi,

After updating from 1.22.6 to 2.2.1 I get this error message when trying to run the golden tests:

```
/flutter_test_listener.NkmyAl/listener.dart:20:21: Error: Getter not found: 'main'.
  await Future(test.main);
                    ^^^^
```
                                                                              
I have updated my `flutter_test_config.dart` so the signature looks like your example app, like this:
```
Future<void> testExecutable(FutureOr<void> Function() testMain) async {
   return GoldenToolkit.runWithConfiguration(...
```
But something is still not working.
All suggestions welcome

**Comment by fatherOfLegends** [comment]
Can you confirm what version of golden_toolkit you are using after updating to 2.2.1?

**Comment by ansolantz** [comment]
I have 0.9.0 in pubspec.yaml. One guess I had was that it is using something old in the flutter_tools folder in the error but I have tried flutter clean a couple of times and that has not made any difference.

**Comment by tsimbalar** [comment]
Not sure this helps, but this rings a bell from a discussion in an old closed PR : https://github.com/eBay/flutter_glove_box/pull/81

**Comment by ansolantz** [comment]
This issue seems like it have resolved itself. I ran all the test cases one by one in Visual Studio and since then it's working.
