### ISSUE TITLE
golden_toolkit: Broken text on RichText golden file

### ISSUE THREAD

**Issue by alberto-sf** [eBay/flutter_glove_box#111]
Hello!

We are using `golden_toolkit` (0.9.0) on Flutter 2.2.0 and we are having issues with the `RichText` widget. Here's a very simple golden:

```dart
testGoldens('Broken', (tester) async {
  const text = Text('Hello world');
  final richText = RichText(
    text: const TextSpan(
      text: 'Hello',
      children: [
        TextSpan(
          text: 'world!',
        ),
      ],
    ),
  );

  final builder = GoldenBuilder.column()
    ..addScenario('Text', text)
    ..addScenario('Rich text', richText);

  await tester.pumpWidgetBuilder(
    builder.build(),
    surfaceSize: const Size.square(180),
  );

  await screenMatchesGolden(tester, 'broken');
});
```

This is the result we get:

![broken](https://user-images.githubusercontent.com/79466623/122971869-d0b15a00-d38f-11eb-94f5-2bede111124c.png)

As you can see, the text inside `Text` is correctly rendered while `RichText` only has white squares. Considering that Flutter's default behavior on golden tests is showing white squares instead of the actual chars, we suspect that (probably) there's an issue in `golden_toolkit` with font files.

We have only found this issue with the `RichText` widget and nowhere else. Is this a known issue? Are we doing something wrong or there might be some digging into the package to figure out where the issue is?

**Comment by fatherOfLegends** [comment]
So behind the scenes the Text widget uses a RichText widget. I am guessing if you provide the RichText with a font from your app it will render correctly. I haven't tried it but you might be able to get this automatically using `Text.rich()`

**Comment by alberto-sf** [comment]
Thank you! Your hint has been very helpful to me.

To solve this issue, I have downloaded a font from Google Fonts (for simplicity, Roboto), imported the `ttf` files and explicitly declared `fontFamily: 'Roboto'` inside each `TextSpan` (using the `Text.rich` constructor). It works!

So I think that in order to make sure that goldens always work with Text, we need at least a font family loaded into Flutter which will be used as "fallback"
