### ISSUE TITLE
Bad state: There is no current invoker.

### ISSUE THREAD

**Issue by rmasarovic** [eBay/flutter_glove_box#121]
Hi i have question when i use GoldenToolkit.runWithConfiguration in flutter_test_config Golden test work. But when i run test where i make simple request i get this error.  **Bad state: There is no current invoker. Please make sure that you are making the call inside a test zone.**   Any idea how handle this state?

**Comment by coreysprague** [comment]
@rmasarovic  Can you provide a sample of what you are trying to do?

**Comment by rmasarovic** [comment]
Here is my test: 

import 'package:http/http.dart' as http;

void main() async{

var config= await http.get(
    Uri.parse("https://www.test.sk"),
  );

test('simpleRequest', () async {
      print("simpleRequest");
    });
}

This work snippet when i dont use GoldenToolkit.runWithConfiguration...

**Comment by rmasarovic** [comment]
Okey i found solution. Now my end to end tests works. 

Here is snippet:

class _MyHttpOverrides extends HttpOverrides {}

void main() async{

  HttpOverrides.global = _MyHttpOverrides();

  var config= await http.get(
    Uri.parse("https://www.test.sk"),
  );

  test('simpleRequest', () async {
    print("simpleRequest");
  });
}

**Comment by coreysprague** [comment]
I'm going to go ahead and close this. Thanks!
