### ISSUE TITLE
Why are my tests failing?

### ISSUE THREAD

**Issue by pablobaldez** [eBay/flutter_glove_box#127]
The tests are working on my machine but when I run on CI (using github actions) 
I'm not changing something to get failures so I'm not understanding why it's happening.
Here are the test code:
```dart
void main() {
  testGoldens(
    'golden simple test',
    (tester) async {
      await loadAppFonts();
      final widget = MaterialApp(
        home: Builder(
          builder: (context) {
            final wealthData =
                NebraskaTheme.of(context).copyWith(ContextTheme.wealth);
            return NebraskaTheme(
              data: wealthData,
              child: Text(
                'data',
                style: wealthData.typography.p4.copyWith(
                  color: wealthData.colors.context.primary,
                ),
              ),
            );
          },
        ),
      );

      await tester.pumpWidget(widget);
      await screenMatchesGolden(tester, 'flutter_demo_page_multiple_scenarios');
    },
  );
}
```
here are the failure message:
```
The following assertion was thrown while running async test code:
Golden "goldens/flutter_demo_page_multiple_scenarios.png": Pixel test failed, 0.03% diff detected.
Failure feedback can be found at /home/runner/work/app/app/packages/nebraska/test/failures
```

and here are the failure images:
<div>
  flutter_demo_page_multiple_scenarios_isolatedDiff
  <img src="https://user-images.githubusercontent.com/7607311/140183031-347de8e6-5d43-4494-9963-62a8d8edd14f.png" width="600"/>
  <br>
  flutter_demo_page_multiple_scenarios_maskedDiff
  <img src="https://user-images.githubusercontent.com/7607311/140183035-d5e81ca1-6f40-4ed5-8103-8f0df16a796c.png" width="600"/>
  <br>
  flutter_demo_page_multiple_scenarios_masterImage
  <img src="https://user-images.githubusercontent.com/7607311/140183037-fcf155b2-561b-4edb-99ee-fe137499e391.png" width="600"/>
  <br>
  flutter_demo_page_multiple_scenarios_testImage
  <img src="https://user-images.githubusercontent.com/7607311/140183042-37a0957c-d6ac-443b-9655-23642ea4afb1.png" width="600"/>
</div>

**Comment by coreysprague** [comment]
are your CI machine and your local machine running the same OS? There are unfortunately OS-specific differences that occur with regards to text rendering.

**Comment by pablobaldez** [comment]
No! You are right, i changed to use the same OS and everything works fine.
Thank you
