### ISSUE TITLE
Pixel test failed threshold

### ISSUE THREAD

**Issue by michael-woolsey** [eBay/flutter_glove_box#150]
Is it possible to have a threshold where if the pixel test diff detected is less than say 1% (configurable) we would allow the test to pass?  

For example, I'm getting this error in one of my tests:
`Golden "goldens/history_tab_screen.png": Pixel test failed, 0.20% diff detected.`

Which in my case, could be a difference between Windows and Linux, could be something else that I just can't see.

This could be global or per test, I just couldn't find a way to do it myself.  Any ideas if this is possible?

Thanks!

**Comment by coreysprague** [comment]
This package just wraps the out of the box golden assertion provided by flutter_test, and currently that API does not provide a means to configure the threshold.

However, there is a way to globally override the default comparison algorithm by setting your own implementation. I have not investigated how challenging it might be to do so.

Here is the API & documentation: https://github.com/flutter/flutter/blob/ee6a693cde504d9db335344b0920b8c9e6f92896/packages/flutter_test/lib/src/goldens.dart#L131

We currently have no plans to add this support for this in golden_toolkit. However, if you, or someone wants to create a less strict Comparator that people can optionally wire in, I'd be happy to review it and add it to the package!

**Comment by michael-woolsey** [comment]
Okay, thank you for the information!
