### ISSUE TITLE
Black borders around material widgets

### ISSUE THREAD

**Issue by jtdLab** [eBay/flutter_glove_box#155]
Hi why are there black borders around some material widgets. Is it possible to disable them?

**Comment by tsimbalar** [comment]
@jtdLab I think you are referring to the shadows, which, in Golden Tests, are opaque instead of translucent .... 

See also : 
- #72 
- #104 

Since #75 there is a configuration option `enableRealShadows` that you can use.

**Comment by jtdLab** [comment]
Thanks a lot.
