### ISSUE TITLE
Golden tests occassionally failing with 0.00% diff

### ISSUE THREAD

**Issue by guy-plentific** [eBay/flutter_glove_box#160]
I am posting this in the hope that someone else has experienced this issue as has an idea of what could be causing it. For apparently no reason, sometimes one or two of our golden tests fail with the error

`Pixel test failed, 0.00% diff`

I have noticed a similar issue here: https://github.com/flutter/devtools/issues/2935

We have ruled out obvious causes (different versions of Flutter, different operating systems etc.) but are hoping that someone else has experienced something similar and can help us.

**Comment by coreysprague** [comment]
@guy-plentific is there any pattern to the tests that are impacted by this? Our app has about 900 golden tests in total, and we haven't encountered this.

**Comment by guy-plentific** [comment]
@coreysprague sorry for the late reply Corey - no, unfortunately there is no particular pattern. I realise there is very little for you to go by on here, I just thought I would mention in case you had seen this before or had any ideas.

**Comment by johannessachse** [comment]
@guy-plentific I can confirm this issue. But I don't have any solution to this.

**Comment by phipps980316** [comment]
Hey @guy-plentific, we started seeing this too with golden tests with 0.00% difference, but it seemed as tho there was a very very small difference in the images for some reason > 0.001%. 

We couldn't determine the reason for it after checking different flutter versions across our CI runners but we added a workaround to allow a the very small difference as it is was very insignificant. 

Details of the workaround can be found here: [Workaround](https://blog.rows.com/p/writing-a-localfilecomparator-with)

**Comment by guy-plentific** [comment]
> Hey @guy-plentific, we started seeing this too with golden tests with 0.00% difference, but it seemed as tho there was a very very small difference in the images for some reason > 0.001%.
> 
> We couldn't determine the reason for it after checking different flutter versions across our CI runners but we added a workaround to allow the very small difference as it is was very insignificant.
> 
> Details of the workaround can be found here: [Workaround](https://blog.rows.com/p/writing-a-localfilecomparator-with)

Thanks a lot Jon!

**Comment by w3ggy** [comment]
Same problem after upgrading Flutter from 3.3.10 to 3.7.0.

Any idea why? Temporarily we set the threshold to 1% but it is not a solution I guess.

**Comment by befirst** [comment]
This: https://github.com/eBay/flutter_glove_box/issues/160#issuecomment-1295031993 doesn't look like the long-term solution to a problem.
