### ISSUE TITLE
Pixel test fails with 0.00% diff 

### ISSUE THREAD

**Issue by Wreos** [eBay/flutter_glove_box#192]
Hello. I have noticed a problem that my test fails in CI with zero diff.
Log output says there is no difference. 

``` ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown while running async test code:
Golden "goldens/home_page.iphone14.png": Pixel test failed, 0.00% diff detected.
Failure feedback can be found at /Users/runner/work/1/s/test/home/view/failures

When the exception was thrown, this was the stack:
#0      LocalFileComparator.compare (package:flutter_test/src/_goldens_io.dart:106:5)
<asynchronous suspension>
#1      MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart:118:32)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from dart:async)

The exception was caught asynchronously.
════════════════════════════════════════════════════════════════════════════════════════════════════
```
I checked failures folder, and failure isolated diff is empty image. If there is no difference, why it might fail?
![home_page iphone14_isolatedDiff](https://github.com/eBay/flutter_glove_box/assets/15965366/093e3934-380b-408d-8cec-a211ec7b98ef)

**Comment by RafaelPlantard** [comment]
Same here!

**Comment by ricardoboss** [comment]
Could be related: https://github.com/flutter/flutter/issues/111675

**Comment by ricardoboss** [comment]
Might also be related: https://github.com/flutter/flutter/issues/111739

**Comment by ricardoboss** [comment]
This article is a good workaround: use a comparer with a threshold you can control.

https://rows.com/blog/post/writing-a-localfilecomparator-with-threshold-for-flutter-golden-tests

**Comment by Wreos** [comment]
> This article is a good workaround: use a comparer with a threshold you can control.
> 
> https://rows.com/blog/post/writing-a-localfilecomparator-with-threshold-for-flutter-golden-tests

Thanks a lot! Custom comparer  fixed this issue.
