### ISSUE TITLE
loadAppFonts() will fail if package does not contain any image assets.

### ISSUE THREAD

**Issue by coreysprague** [eBay/flutter_glove_box#31]
For a currently unknown reason, if a package does not contain any images, then the FontManifest.json is not generated, even if it depends on other packages with fonts/images 

We need to investigate if this is a bug in Flutter or working as intended. If working as intended, we may need to come up with an alternative solution for loading fonts.

**Comment by coreysprague** [comment]
As a work-around, you can specify an empty assets folder:

```
flutter:
  uses-material-design: true
  # currently needed even though this package doesn't have any images. Without assets,
  # the FontManifest.json isn't created this is likely a Flutter bug
  assets:
    - images/
```

**Comment by coreysprague** [comment]
filed a flutter issue to resolve this, or to provide better clarity on how we should achieve the same end: https://github.com/flutter/flutter/issues/60012

**Comment by Rodsevich** [comment]
Maybe including this in the documentation would be helpful (I have been hours trying to solve the problem with that .json not generated)

**Comment by Rodsevich** [comment]
I've made a PR for updating the docs ( #78 )

**Comment by creativecreatorormaybenot** [comment]
Thanks so much for creating this issue 😂  I figured that it would be something like this, however, I was still a bit lost.

**Comment by coreysprague** [comment]
this appears to be fixed in flutter. I have not tested yet. Will verify before closing this out

**Comment by coreysprague** [comment]
this is fixed in Flutter 2.5, and this workaround is no longer needed!

**Comment by fatherOfLegends** [comment]
@coreysprague can this be closed?

**Comment by coreysprague** [comment]
yup! thanks @fatherOfLegends
