### ISSUE TITLE
Provide a way to customize golden file name

### ISSUE THREAD

**Issue by christian-muertz** [eBay/flutter_glove_box#45]
Currently the golden file name is set to:

```
final fileName = 'goldens/$goldenFileName.png';
```

Which forces the golden files to be in the `golden` directory which is not optimal for some setups.

It would be nice if you could provide sth. like a fileNameBuilder/Factory which is simply a function that takes in a goldenFileName and outputs the actual golden file name. To make the change backwards compatible it should default to:
```
String defaultFileNameFactory(String goldenFileName) {
  return 'goldens/$goldenFileName.png';
}
```

This would enable other testing setups to put the files in another directory :D

**Comment by christian-muertz** [comment]
Something similar would be helpful for `multiScreenGolden` as well! The factory should take the device as well as the golden file name here.

**Comment by christian-muertz** [comment]
This would also enable one to structure the files differently. For example:

```
- goldens/phone/page1.png
- goldens/phone/page2.png

- goldens/tablet/page1.png
- goldens/tablet/page2.png

- goldens/desktop/page1.png
- goldens/desktop/page2.png
```

**Comment by matthew-carroll** [comment]
I'd appreciate this feature as well. I have a directory structure for my goldens which does not use a global /golden directory, so I can't use this package in its current form.
