### ISSUE TITLE
"Basic golden test for empty container Animation test with CustomPump Golden" is failing for me since day 1

### ISSUE THREAD

**Issue by christian-muertz** [eBay/flutter_glove_box#46]
The " Basic golden test for empty container Animation test with CustomPump Golden" test fails with a diff of 3.06% for me since the first commit.

Could anyone confirm that?

**Comment by christian-muertz** [comment]
Seems like the issue is on my side

**Comment by coreysprague** [comment]
@christian-muertz can this be closed?

**Comment by christian-muertz** [comment]
@coreysprague It seems to be a version problem. Seems you guys use `v1.17.1` (ref f7a6a79), which once was on the stable channel. Try to checkout the latest master and run the tests. They will fail. Must be a breaking change in the flutter repo. Checking out the latest stable also fails.

**Comment by christian-muertz** [comment]
Therefore we should probably realign this test to the latest stable ref

**Comment by coreysprague** [comment]
@christian-muertz I checked on the 1.17.3 and v1.17.4, and the tests are all still passing for me.

I wonder if this is less about flutter version and perhaps a platform difference. What OS are you running the tests on?
