### ISSUE TITLE
Expose public API for device sizing even when using standard golden tests

### ISSUE THREAD

**Issue by matthew-carroll** [eBay/flutter_glove_box#51]
This package contains some code that configures the size of the test canvas to replicate a "phone", "tablet", or "iphone11". It would be nice if this functionality was made public in a usable manner for golden tests that do not use a `GoldenBuilder`.

I'm not currently using the `GoldenBuilder` because for me that builder is overly specified - I want some golden tests that aren't columns or grids. But I would like to easily size the canvas to match a device. At the moment I copied that code from this package, but I'd rather just directly use that code within this package.

**Comment by coreysprague** [comment]
@matthew-carroll are you specifically thinking of this bit of logic?

https://github.com/eBay/flutter_glove_box/blob/master/packages/golden_toolkit/lib/src/multi_screen_golden.dart#L83

**Comment by matthew-carroll** [comment]
Yep, that and also the fake padding beneath it because its referenced, too.

I copied that part to my own project so that I could easily render device sizes using the standard approach to goldens.

There is also reset logic, too, which undoes what that referenced function does.

**Comment by coreysprague** [comment]
how would you envision that API?

Ideally, I prefer it as a wrapper function (as the current private extension does) in that it forces the test to clean itself up. 

although some might love how that reads in their tests.

I could expose:

```dart
tester.simulateDevice(device, (tester) { });
```

or could expose:

```dart
tester.simulateDevice(device);

tester.reset();
```

or both 😉 

any thoughts on what would be most beneficial?

**Comment by matthew-carroll** [comment]
I think I'd prefer the 2nd approach which provides direct control. When a callback function is used, I'm never quite sure what's being done in there, and those functions tend to grow with additional behavior over time, which ends up being entirely opt-in or opt-out.

Also you may want both of those methods to make it clear in their name that they apply to the canvas or dimensions of the golden. For example, we're not simulating push notifications or device chrome or anything...

**Comment by coreysprague** [comment]
@Matthew-carroll I exposed a few APIs as part of https://github.com/eBay/flutter_glove_box/pull/58, they will be going out with the next release (which will hopefully be today or tomorrow). Let me know if there is anything else you'd like to see!
