### ISSUE TITLE
Scaffold seems not supported with scenario

### ISSUE THREAD

**Issue by MizukiAsakura** [eBay/flutter_glove_box#64]
It seems that Scaffold and any widgets including Scaffold are not supported when attempt to create a grid or column scenario.

This generate multiple rendering exception when attempt to generate references images by `flutter test --update-goldens --name=Golden`

**Comment by coreysprague** [comment]
@MizukiAsakura we didn't intend for GoldenBuilder to be used with full screens... take a look at the multiScreenGolden

**Comment by coreysprague** [comment]
I think this will get fixed by this enhancement from @moonytoes29 in #68

**Comment by coreysprague** [comment]
check out the new DeviceBuilder api with 0.7.0
