### ISSUE TITLE
VS Code launch configuration: Property template is not allowed

### ISSUE THREAD

**Issue by bsr203** [eBay/flutter_glove_box#69]
Hi,
[In the instruction](https://github.com/eBay/flutter_glove_box/tree/master/packages/golden_toolkit#configure-vs-code), it says to add below launch configuration.
```
"configurations": [
    {
      "name": "Golden",
      "request": "launch",
      "type": "dart",
      "template": "run-test",
      "args": ["--update-goldens"]
    }
```

but, when I add, it say `Property template is not allowed.`. VS Code version 1.50.1

Is there an updated configuration?

**Comment by coreysprague** [comment]
@bsr203

template still works despite the warning. That being said... looks like the dart plugin changed their schema...

Just tested, and the following works:

```json
{
      "name": "Golden",
      "request": "launch",
      "type": "dart",
      "codeLens": {
        "for": [
          "run-test",     
          "run-test-file"
        ]
      },
      "args": [
        "--update-goldens"
      ]
    }
```

**Comment by coreysprague** [comment]
I'll update the docs. Thanks!
