### ISSUE TITLE
Support for "real shadows"

### ISSUE THREAD

**Issue by tsimbalar** [eBay/flutter_glove_box#72]
Hi,

first, many thanks for this project, we started to use it this week, it's already paying off !

One of the things that we quickly noticed while adding coverage for the components library we share between applications was that shadows were rendering in a strange way, and appeared as "opaque" blocks. 

After a bit of digging, I understand that, "by design", when running widget tests, shadows are rendered as solid blocks  : 

> since the rendering of shadows is not guaranteed to be pixel-for-pixel identical from version to version (or even from run to run).

(see https://api.flutter.dev/flutter/painting/debugDisableShadows.html ).

I found this trick to temporarily "re-enable" real shadows for a given test : https://stackoverflow.com/a/64675795/474763 and indeed it does the trick.

To make it a bit easier to apply across our tests, I ended up creating a small helper function like 

```dart
/// by default, Widget tests use opaque shadows to avoid golden test failures
/// we do want those on some tests to have images that look closer to reality
/// see https://stackoverflow.com/a/64675795/474763
Future<void> runWithRealShadows(Future<void> Function() callback) async {
  try {
    debugDisableShadows = false;
    await callback();
  } finally {
    debugDisableShadows = true;
  }
}
```

and using it in pretty much all my `testGoldens` tests like so : 

```dart
void main() {
  testGoldens('Boxes Demo', (tester) async {
    await runWithRealShadows(() async {
      await tester.pumpWidgetBuilder(
        BoxesDemo(),
        wrapper: designSystemWrapper,
      );
      await screenMatchesGolden(
        tester,
        'boxes_demo',
      );
    });
  });
}
```

This is fine for now, and does the job, but I'm wondering if, since `testGoldens` functions are already a wrapper around `testWidgets` , there would be away to package this functionality as part of `golden_toolkit` , so that we would be able to : 
- enable "real shadows" once and for all in the whole project (by setting it one in `flutter_test_config.dart` )
- maybe exposing it on `GoldenToolkitConfiguration` so it can be applied temporarily through `GoldenToolkit.runWithConfiguration()`

So I think that would be a nice addition to this library. If you think so too, I'd be happy to try and come up with a PR with an initial proposal of what it could look like.

**Comment by fatherOfLegends** [comment]
@coreysprague I think this looks like a good idea. Any concerns you can think of?

**Comment by coreysprague** [comment]
That makes sense to me... exposing a property on the configuration object seems like a natural place to put it. I would leave the default value to "off" and have it be an opt-in feature.

btw, glad to hear you are finding value in the package 😄

**Comment by tsimbalar** [comment]
I have a PR for this here : https://codecov.io/github/eBay/flutter_glove_box/commit/90cb227a3bc0913f9a864050af719c6a08736c7c :)
