### ISSUE TITLE
Release v0.7.0 does not appear in GitHub releases

### ISSUE THREAD

**Issue by tsimbalar** [eBay/flutter_glove_box#73]
I see on https://github.com/eBay/flutter_glove_box/releases that the latest release is `0.6.0` , but on https://pub.dev/packages/golden_toolkit , `0.7.0` is showing.

I guess it's a matter of adding a tag to the git repo :)

**Comment by coreysprague** [comment]
I'm really lazy about that... need to spend the time to automate this part of the process. Thanks!

done!
