### ISSUE TITLE
Missing null safety support / Library is legacy

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [eBay/flutter_glove_box#90]
Trying to use `golden_toolkit` with a null safe library will generate the following warning:

>The library 'package:golden_toolkit/golden_toolkit.dart' is legacy, and should not be imported into a null safe library.  Try migrating the imported library.

This is because there is no `-nullsafety` version for `golden_toolkit` yet.

Quoting from the email that has been sent to applicable package authors:

>You can find information on the migration at [dart.dev/null-safety](https://dart.dev/null-safety), including links to a [migration guide](https://dart.dev/null-safety/migration-guide) and [frequently asked questions](https://dart.dev/null-safety/faq).

**Comment by mZadorskii** [comment]
I think we decided to keep a separate branch for null safe version for now

**Comment by creativecreatorormaybenot** [comment]
@mZadorskii That is fine - you should still create it and publish it as `golden_toolkit` `0.9.0-nullsafety.0`.

This will add a **separate** pre-release on Pub that can be used be null safe packages depending on it :)

**Comment by tsimbalar** [comment]
I believe this is in progress : https://github.com/eBay/flutter_glove_box/pull/88

**Comment by creativecreatorormaybenot** [comment]
@tsimbalar Thanks, I see 👍

**Comment by coreysprague** [comment]
I'm going to publish this now

**Comment by coreysprague** [comment]
![image](https://user-images.githubusercontent.com/5420324/100644264-f42b8f00-32ef-11eb-85c6-b2c08534559a.png)

published the prerelease this morning. Sorry for the delay. I didn't touch a computer for the long holiday weekend 😄
