### ISSUE TITLE
change main to testExcutable on flutter_test_config

### ISSUE THREAD

**Issue by fredgrott** [eBay/flutter_glove_box#98]
This just bit me on the flutter beta channel..need the change going forward past flutter 1.22

Thanks for creating a very useful plugin!

**Comment by fatherOfLegends** [comment]
This is something we are aware of. I believe it was fixed in #88 but it is only in - alpha prerelease. https://pub.dev/packages/golden_toolkit/versions/0.9.0-nullsafety.0/changelog

**Comment by fatherOfLegends** [comment]
Fixed in #99
